pipeline {
    agent any

    stages {
        stage('1. Kodu Cek (Checkout)') {
            steps {
                // Jenkins bu adimda GitHub'daki kodlari Rocky Linux'a indirir
                checkout scm
            }
        }

        stage('2. Altyapiyi Docker Compose ile Tetikle') {
            steps {
                script {
                    echo 'Docker Compose hattı baslatiliyor...'
                    echo 'Eski konteynerler temizleniyor, imajlar derleniyor ve sistem ayaga kaldiriliyor...'
                    // Projenin kök dizinindeki docker-compose.yml dosyasını ayaga kaldirir
                    sh "docker-compose up --build -d"
                }
            }
        }
    }

    post {
        success {
            echo 'Tebrikler! Docker Compose mimarisi basariyla ayaga kalkti.'
        }
        failure {
            echo 'Eyvah! Derleme veya dagitim sirasinda bir hata olustu.'
        }
    }
}